load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "basable_messenger",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "basable_messenger",
    visibility = ["//visibility:public"],
)

rust_test(
    name = "basable_messenger_test",
    crate = ":basable_messenger",
)
