//! The two generated crates, as Rust source. Both are token streams built
//! with `quote`, parsed back into a `syn::File` (so a generator bug is a
//! syntax error here, not in the tenant's build) and printed by
//! `prettyplease`.
//!
//! - `interfaces` (depends on `messages` and `basable-messenger` only): per
//!   nanoservice a `<Pascal>Routes` bound (one `Route` per declared send,
//!   plus `Sync`, with a blanket impl), a `<Pascal>Sender<'a, R>` exposing
//!   exactly the declared `send_<snake message>` calls, and, when it
//!   handles anything, a `<Pascal>Handler<R: <Pascal>Routes>` trait with one
//!   `handle_<snake message>` per handled message; and `source::<Pascal>`,
//!   the marker that keys the routes of each nanoservice.
//! - `messenger` (depends on every nanoservice crate): the concrete router
//!   holding every nanoservice's component (`<name>::<Pascal>`) as a
//!   private field, `new` in declaration order, one accessor per field, and
//!   one `Route` impl per declared `(source, message)` pair, boxed on the
//!   routes the cycle analysis chose.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::graph::{Analysis, RouteKey};
use crate::names::{last_segment, pascal, snake};
use crate::spec::{Kind, Nanoservice};

/// The header every generated file starts with.
pub const HEADER: &str = "// GENERATED by basable-messenger-gen from routing.yaml. DO NOT EDIT.\n// Edit routing.yaml and rebuild; the build regenerates this file.\n\n";

/// Which generated crate.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Crate {
    /// `crates/interfaces/src/lib.rs`.
    Interfaces,
    /// `crates/messenger/src/lib.rs`.
    Messenger,
}

impl Crate {
    /// The crate's name, as on the command line.
    pub fn name(self) -> &'static str {
        match self {
            Crate::Interfaces => "interfaces",
            Crate::Messenger => "messenger",
        }
    }

    /// Parses a command-line name.
    pub fn from_name(s: &str) -> Option<Crate> {
        match s {
            "interfaces" => Some(Crate::Interfaces),
            "messenger" => Some(Crate::Messenger),
            _ => None,
        }
    }
}

/// A generator bug: the emitted tokens did not parse as a file.
#[derive(Debug)]
pub struct EmitError {
    /// The parse error.
    pub error: syn::Error,
    /// The tokens, for the report.
    pub tokens: String,
}

impl std::fmt::Display for EmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "the generator emitted Rust that does not parse ({}); this is a bug in basable-messenger-codegen:\n{}",
            self.error, self.tokens
        )
    }
}

impl std::error::Error for EmitError {}

/// Emits one generated crate's `src/lib.rs`.
pub fn emit(a: &Analysis<'_>, which: Crate) -> Result<String, EmitError> {
    let tokens = match which {
        Crate::Interfaces => interfaces(a),
        Crate::Messenger => messenger(a),
    };
    let file = syn::parse2::<syn::File>(tokens.clone()).map_err(|error| EmitError {
        error,
        tokens: tokens.to_string(),
    })?;
    Ok(format!("{HEADER}{}", prettyplease::unparse(&file)))
}

struct Types {
    error: syn::Type,
    ctx: syn::Type,
}

impl Types {
    fn of(a: &Analysis<'_>) -> Types {
        Types {
            error: parse_type(&a.spec.messenger.error_type),
            ctx: parse_type(&a.spec.messenger.ctx_type),
        }
    }

    /// The response type of a declaration kind.
    fn response(&self, kind: &Kind) -> TokenStream {
        let error = &self.error;
        match kind {
            Kind::Typed(t) => {
                let t = parse_type(t);
                quote!(Result<#t, #error>)
            }
            Kind::ErrorFanout => quote!(Result<(), #error>),
            Kind::Void => quote!(()),
        }
    }
}

fn parse_type(s: &str) -> syn::Type {
    syn::parse_str(s).expect("Spec::parse checked every type")
}

fn parse_path(s: &str) -> syn::Path {
    syn::parse_str(s).expect("Spec::parse checked every message path")
}

fn uses(a: &Analysis<'_>) -> TokenStream {
    let items = a.spec.messenger.uses.iter().map(|u| {
        let tree: syn::UseTree = syn::parse_str(u).expect("Spec::parse checked every use");
        quote!(use #tree;)
    });
    quote!(#(#items)*)
}

fn source_ident(n: &Nanoservice) -> syn::Ident {
    format_ident!("{}", pascal(&n.name))
}

fn method_suffix(message: &str) -> String {
    snake(last_segment(message))
}

fn doc(text: String) -> TokenStream {
    quote!(#[doc = #text])
}

/// The route bound of one send: `Route<M, Resp, source::X, Ctx>`.
fn route_bound(types: &Types, source: &syn::Ident, message: &str, kind: &Kind) -> TokenStream {
    let m = parse_path(message);
    let resp = types.response(kind);
    let ctx = &types.ctx;
    quote!(::basable_messenger::Route<#m, #resp, source::#source, #ctx>)
}

fn interfaces(a: &Analysis<'_>) -> TokenStream {
    let types = Types::of(a);
    let uses = uses(a);
    let ctx = &types.ctx;

    let sources = a.spec.nanoservices.iter().map(|n| {
        let ident = source_ident(n);
        let d = doc(format!(
            " The source marker of `{}`: keys its routes.",
            n.name
        ));
        quote! {
            #d
            #[derive(Debug, Clone, Copy, PartialEq, Eq)]
            pub struct #ident;
        }
    });

    let per_nanoservice = a.spec.nanoservices.iter().map(|n| {
        let p = pascal(&n.name);
        let source = source_ident(n);
        let routes = format_ident!("{p}Routes");
        let sender = format_ident!("{p}Sender");
        let handler = format_ident!("{p}Handler");

        let bounds: Vec<TokenStream> = n
            .sends
            .iter()
            .map(|d| route_bound(&types, &source, &d.message, &d.kind()))
            .collect();
        let routes_doc = doc(format!(
            " What `{}` needs of the router: a route for each of its {} declared send(s). Every router the generator emits satisfies it (blanket impl).",
            n.name,
            n.sends.len()
        ));
        let sender_doc = doc(format!(
            " The sender of `{}`: exactly its declared sends, each a direct call into the router's route.",
            n.name
        ));

        let send_methods = n.sends.iter().map(|d| {
            let m = parse_path(&d.message);
            let kind = d.kind();
            let resp = types.response(&kind);
            let name = format_ident!("send_{}", method_suffix(&d.message));
            let bound = route_bound(&types, &source, &d.message, &kind);
            let what = match kind {
                Kind::Typed(_) => "a 1:1 request",
                Kind::ErrorFanout => "a fail-fast error fan-out (handlers in declaration order, the first error returns)",
                Kind::Void => "a void fan-out (every handler in declaration order)",
            };
            let d = doc(format!(" Sends `{}`: {what}.", d.message));
            // A void send has no `-> ()` (clippy::unused_unit).
            let ret = if kind == Kind::Void {
                quote!()
            } else {
                quote!(-> #resp)
            };
            quote! {
                #d
                pub async fn #name(&self, ctx: &#ctx, msg: #m) #ret {
                    <R as #bound>::route(self.0, ctx, msg).await
                }
            }
        });
        let send_impl = if n.sends.is_empty() {
            quote!()
        } else {
            quote! {
                impl<'a, R: #routes> #sender<'a, R> {
                    #(#send_methods)*
                }
            }
        };

        let handler_trait = if n.handles.is_empty() {
            quote!()
        } else {
            let methods = n.handles.iter().map(|d| {
                let m = parse_path(&d.message);
                let kind = d.kind();
                let resp = types.response(&kind);
                let name = format_ident!("handle_{}", method_suffix(&d.message));
                let what = match kind {
                    Kind::Typed(_) => "the one handler of this 1:1 request",
                    Kind::ErrorFanout => "one handler of this error fan-out; an `Err` stops the fan-out",
                    Kind::Void => "one handler of this void fan-out",
                };
                let d = doc(format!(" Handles `{}`: {what}. `s` is this nanoservice's sender.", d.message));
                quote! {
                    #d
                    fn #name(
                        &self,
                        ctx: &#ctx,
                        msg: #m,
                        s: #sender<'_, R>,
                    ) -> impl ::std::future::Future<Output = #resp> + Send;
                }
            });
            let handler_doc = doc(format!(
                " What `{}` implements: one method per handled message, generic over the router it sends through. The future is `Send`, so a `std::sync::MutexGuard` cannot be held across a send.",
                n.name
            ));
            quote! {
                #handler_doc
                pub trait #handler<R: #routes>: Send + Sync {
                    #(#methods)*
                }
            }
        };

        quote! {
            #routes_doc
            pub trait #routes: #(#bounds +)* Sync {}
            impl<T> #routes for T where T: #(#bounds +)* Sync {}

            #sender_doc
            pub struct #sender<'a, R>(&'a R);

            impl<'a, R> Clone for #sender<'a, R> {
                fn clone(&self) -> Self {
                    *self
                }
            }

            impl<'a, R> Copy for #sender<'a, R> {}

            impl<'a, R> #sender<'a, R> {
                /// Wraps the router. The messenger constructs one per handled
                /// message; a sends-only nanoservice constructs its own from
                /// the `&'static` router it was handed.
                pub fn new(router: &'a R) -> Self {
                    #sender(router)
                }
            }

            #send_impl

            #handler_trait
        }
    });

    quote! {
        #![allow(unused_imports, dead_code, clippy::needless_lifetimes)]
        #uses

        /// The source markers, one per nanoservice.
        pub mod source {
            #(#sources)*
        }

        #(#per_nanoservice)*
    }
}

fn messenger(a: &Analysis<'_>) -> TokenStream {
    let types = Types::of(a);
    let uses = uses(a);
    let name = format_ident!("{}", a.spec.messenger.name);

    let component = |n: &Nanoservice| -> (syn::Ident, TokenStream) {
        let field = format_ident!("{}", n.name);
        let ty_name = format_ident!("{}", pascal(&n.name));
        (field.clone(), quote!(#field::#ty_name))
    };

    let fields = a.spec.nanoservices.iter().map(|n| {
        let (field, ty) = component(n);
        quote!(#field: #ty,)
    });
    let params = a.spec.nanoservices.iter().map(|n| {
        let (field, ty) = component(n);
        quote!(#field: #ty,)
    });
    let inits = a.spec.nanoservices.iter().map(|n| {
        let (field, _) = component(n);
        quote!(#field,)
    });
    let accessors = a.spec.nanoservices.iter().map(|n| {
        let (field, ty) = component(n);
        let d = doc(format!(
            " The `{}` component (for the composition root: workers, the Connect server).",
            n.name
        ));
        quote! {
            #d
            pub fn #field(&self) -> &#ty {
                &self.#field
            }
        }
    });
    let sync_checks = a.spec.nanoservices.iter().map(|n| {
        let (_, ty) = component(n);
        quote!(check::<#ty>();)
    });

    let routes = a
        .routes()
        .into_iter()
        .map(|key| route_impl(a, &types, &name, &key));

    let struct_doc = doc(format!(
        " The router: every nanoservice's component, and one `Route` impl per declared `(source, message)` pair. Fields are private, so a handler holding `&{}` reaches only its own sender.",
        a.spec.messenger.name
    ));

    quote! {
        #![allow(unused_imports, clippy::needless_lifetimes)]
        use ::basable_messenger::{boxed, Route};
        use ::interfaces::source;
        #uses

        #struct_doc
        pub struct #name {
            #(#fields)*
        }

        impl #name {
            /// Builds the router from every component, in `routing.yaml` order.
            pub fn new(#(#params)*) -> Self {
                #name { #(#inits)* }
            }

            #(#accessors)*
        }

        // Every component is shared by reference between concurrent
        // handlers and reconcilers; a component that is not Send + Sync is
        // named here, not deep inside a route's future.
        #[allow(dead_code)]
        fn assert_components_are_send_and_sync() {
            fn check<T: Send + Sync>() {}
            #(#sync_checks)*
        }

        #(#routes)*
    }
}

fn route_impl(a: &Analysis<'_>, types: &Types, name: &syn::Ident, key: &RouteKey) -> TokenStream {
    let source_n = &a.spec.nanoservices[key.source];
    let source = source_ident(source_n);
    let info = a.message(&key.message);
    let m = parse_path(&key.message);
    let resp = types.response(&info.kind);
    let ctx = &types.ctx;
    let suffix = method_suffix(&key.message);
    let handle = format_ident!("handle_{suffix}");

    let call = |h: usize, msg: TokenStream| -> TokenStream {
        let hn = &a.spec.nanoservices[h];
        let field = format_ident!("{}", hn.name);
        let p = pascal(&hn.name);
        let trait_name = format_ident!("{p}Handler");
        let sender = format_ident!("{p}Sender");
        quote! {
            ::interfaces::#trait_name::<#name>::#handle(
                &self.#field, ctx, #msg, ::interfaces::#sender::new(self),
            ).await
        }
    };
    let handlers: Vec<usize> = info.handlers.iter().map(|h| h.nanoservice).collect();
    let last = handlers.len().saturating_sub(1);
    let body = match info.kind {
        Kind::Typed(_) => {
            let h = handlers[0];
            let c = call(h, quote!(msg));
            quote!(#c)
        }
        Kind::Void => {
            if handlers.is_empty() {
                quote! {
                    let _ = (ctx, msg);
                }
            } else {
                let calls = handlers.iter().enumerate().map(|(i, &h)| {
                    let msg = if i < last {
                        quote!(msg.clone())
                    } else {
                        quote!(msg)
                    };
                    let c = call(h, msg);
                    quote!(#c;)
                });
                quote!(#(#calls)*)
            }
        }
        Kind::ErrorFanout => {
            if handlers.is_empty() {
                quote! {
                    let _ = (ctx, msg);
                    Ok(())
                }
            } else {
                let calls = handlers.iter().enumerate().map(|(i, &h)| {
                    let msg = if i < last {
                        quote!(msg.clone())
                    } else {
                        quote!(msg)
                    };
                    let c = call(h, msg);
                    quote!(#c?;)
                });
                quote! {
                    #(#calls)*
                    Ok(())
                }
            }
        }
    };
    // An unboxed route is a plain `async fn` (clippy::manual_async_fn); a
    // boxed one must spell the return type, because it returns the
    // `Pin<Box<dyn Future>>` that erases the inner future.
    let ret = if info.kind == Kind::Void {
        quote!()
    } else {
        quote!(-> #resp)
    };
    let method = if a.is_boxed(key) {
        quote! {
            fn route<'a>(
                &'a self,
                ctx: &'a #ctx,
                msg: #m,
            ) -> impl ::std::future::Future<Output = #resp> + Send + 'a {
                boxed(async move { #body })
            }
        }
    } else {
        quote! {
            async fn route(&self, ctx: &#ctx, msg: #m) #ret {
                #body
            }
        }
    };
    let handler_names: Vec<&str> = handlers
        .iter()
        .map(|&h| a.spec.nanoservices[h].name.as_str())
        .collect();
    let shape = match info.kind {
        Kind::Typed(_) => format!("1:1 to `{}`", handler_names.join(", ")),
        Kind::ErrorFanout => format!("fail-fast error fan-out to [{}]", handler_names.join(", ")),
        Kind::Void => format!("void fan-out to [{}]", handler_names.join(", ")),
    };
    let boxed_note = if a.is_boxed(key) {
        "; boxed, because this route closes a cycle (W_ROUTE_CYCLE)"
    } else {
        ""
    };
    let d = doc(format!(
        " `{}` sent by `{}`: {shape}{boxed_note}.",
        key.message, source_n.name
    ));
    quote! {
        #d
        impl Route<#m, #resp, source::#source, #ctx> for #name {
            #method
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::analyze;
    use crate::spec::Spec;

    const HEAD: &str = "version: 1\nmessenger:\n  name: Messenger\n  rust:\n    error_type: AppError\n    ctx_type: Ctx\n    uses: [\"messages::*\"]\n";

    fn emitted(body: &str, which: Crate) -> String {
        let spec = Spec::parse(&format!("{HEAD}{body}")).unwrap();
        let a = analyze(&spec);
        emit(&a, which).unwrap()
    }

    /// The port of error_fanout_test.go's TestGenerateErrorFanoutIsOrderedAndFailFast.
    #[test]
    fn an_error_fanout_calls_handlers_in_declaration_order_and_fails_fast() {
        let text = emitted(
            "nanoservices:\n  - name: sender\n    sends:\n      - { message: Event, response: error }\n  - name: first\n    handles:\n      - { message: Event, response: error }\n  - name: second\n    handles:\n      - { message: Event, response: error }\n",
            Crate::Messenger,
        );
        let first = text.find("&self.first").expect("first handler called");
        let second = text.find("&self.second").expect("second handler called");
        assert!(
            first < second,
            "handlers are not generated in declaration order:\n{text}"
        );
        assert_eq!(
            text.matches(".await?;").count(),
            2,
            "every guarded handler call propagates the first error:\n{text}"
        );
        assert!(
            text.contains("Ok(())"),
            "the route is not fail-fast:\n{text}"
        );
        assert!(
            text.contains("msg.clone()"),
            "a fan-out clones the message for all but the last handler:\n{text}"
        );
    }

    #[test]
    fn the_interfaces_crate_names_the_scaffolds_methods() {
        let text = emitted(
            "nanoservices:\n  - name: order_ops\n    sends:\n      - { message: GetProductRequest, response: Product }\n      - { message: OrderEvent }\n  - name: catalog\n    handles:\n      - { message: GetProductRequest, response: Product }\n      - { message: OrderEvent }\n",
            Crate::Interfaces,
        );
        assert!(text.starts_with(HEADER));
        assert!(text.contains("pub struct OrderOps;"), "{text}");
        assert!(text.contains("pub trait OrderOpsRoutes:"), "{text}");
        assert!(
            text.contains("pub struct OrderOpsSender<'a, R>(&'a R);"),
            "{text}"
        );
        assert!(
            text.contains("pub async fn send_get_product_request("),
            "{text}"
        );
        assert!(text.contains("pub async fn send_order_event("), "{text}");
        assert!(
            text.contains("pub trait CatalogHandler<R: CatalogRoutes>: Send + Sync"),
            "{text}"
        );
        assert!(text.contains("fn handle_get_product_request("), "{text}");
        assert!(
            text.contains(
                "-> impl ::std::future::Future<Output = Result<Product, AppError>> + Send;"
            ),
            "{text}"
        );
        assert!(
            text.contains("-> impl ::std::future::Future<Output = ()> + Send;"),
            "{text}"
        );
        // A sends-only nanoservice has no handler trait.
        assert!(!text.contains("pub trait OrderOpsHandler"), "{text}");
        // A handles-only nanoservice still has a sender, with no sends.
        assert!(
            text.contains("pub struct CatalogSender<'a, R>(&'a R);"),
            "{text}"
        );
    }

    #[test]
    fn a_boxed_route_wraps_its_future_and_the_others_do_not() {
        let text = emitted(
            "nanoservices:\n  - name: a\n    handles:\n      - { message: Ping, response: R }\n    sends:\n      - { message: Pong, response: R }\n  - name: b\n    handles:\n      - { message: Pong, response: R }\n    sends:\n      - { message: Ping, response: R }\n",
            Crate::Messenger,
        );
        assert_eq!(text.matches("boxed(async move {").count(), 1, "{text}");
        assert_eq!(text.matches("impl Route<").count(), 2, "{text}");
        assert!(text.contains("pub struct Messenger {"), "{text}");
        assert!(text.contains("a: a::A,"), "{text}");
        assert!(
            text.contains("pub fn new(a: a::A, b: b::B) -> Self"),
            "{text}"
        );
        assert!(text.contains("check::<a::A>();"), "{text}");
    }

    #[test]
    fn a_void_fanout_with_no_handler_consumes_its_arguments() {
        let text = emitted(
            "nanoservices:\n  - name: a\n    sends:\n      - { message: Event }\n",
            Crate::Messenger,
        );
        assert!(text.contains("let _ = (ctx, msg);"), "{text}");
    }
}
