[package]
name = "messages"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
basable-core = { workspace = true }
basable-publicid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
