// GENERATED by basable-messenger-gen from routing.yaml. DO NOT EDIT.
// Edit routing.yaml and rebuild; the build regenerates this file.

#![allow(unused_imports, dead_code, clippy::needless_lifetimes)]
use messages::*;
/// The source markers, one per nanoservice.
pub mod source {
    /// The source marker of `catalog`: keys its routes.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct Catalog;
    /// The source marker of `order`: keys its routes.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct Order;
    /// The source marker of `notifier`: keys its routes.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct Notifier;
    /// The source marker of `api`: keys its routes.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct Api;
}
/// What `catalog` needs of the router: a route for each of its 0 declared send(s). Every router the generator emits satisfies it (blanket impl).
pub trait CatalogRoutes: Sync {}
impl<T> CatalogRoutes for T
where
    T: Sync,
{}
/// The sender of `catalog`: exactly its declared sends, each a direct call into the router's route.
pub struct CatalogSender<'a, R>(&'a R);
impl<'a, R> Clone for CatalogSender<'a, R> {
    fn clone(&self) -> Self {
        *self
    }
}
impl<'a, R> Copy for CatalogSender<'a, R> {}
impl<'a, R> CatalogSender<'a, R> {
    /// Wraps the router. The messenger constructs one per handled
    /// message; a sends-only nanoservice constructs its own from
    /// the `&'static` router it was handed.
    pub fn new(router: &'a R) -> Self {
        CatalogSender(router)
    }
}
/// What `catalog` implements: one method per handled message, generic over the router it sends through. The future is `Send`, so a `std::sync::MutexGuard` cannot be held across a send.
pub trait CatalogHandler<R: CatalogRoutes>: Send + Sync {
    /// Handles `UpsertProductRequest`: the one handler of this 1:1 request. `s` is this nanoservice's sender.
    fn handle_upsert_product_request(
        &self,
        ctx: &basable_core::Ctx,
        msg: UpsertProductRequest,
        s: CatalogSender<'_, R>,
    ) -> impl ::std::future::Future<
        Output = Result<Product, basable_core::AppError>,
    > + Send;
    /// Handles `GetProductRequest`: the one handler of this 1:1 request. `s` is this nanoservice's sender.
    fn handle_get_product_request(
        &self,
        ctx: &basable_core::Ctx,
        msg: GetProductRequest,
        s: CatalogSender<'_, R>,
    ) -> impl ::std::future::Future<
        Output = Result<Product, basable_core::AppError>,
    > + Send;
    /// Handles `OrderEvent`: one handler of this void fan-out. `s` is this nanoservice's sender.
    fn handle_order_event(
        &self,
        ctx: &basable_core::Ctx,
        msg: OrderEvent,
        s: CatalogSender<'_, R>,
    ) -> impl ::std::future::Future<Output = ()> + Send;
}
/// What `order` needs of the router: a route for each of its 3 declared send(s). Every router the generator emits satisfies it (blanket impl).
pub trait OrderRoutes: ::basable_messenger::Route<
        GetProductRequest,
        Result<Product, basable_core::AppError>,
        source::Order,
        basable_core::Ctx,
    > + ::basable_messenger::Route<
        SendNotificationRequest,
        Result<NotificationReceipt, basable_core::AppError>,
        source::Order,
        basable_core::Ctx,
    > + ::basable_messenger::Route<
        OrderEvent,
        (),
        source::Order,
        basable_core::Ctx,
    > + Sync {}
impl<T> OrderRoutes for T
where
    T: ::basable_messenger::Route<
            GetProductRequest,
            Result<Product, basable_core::AppError>,
            source::Order,
            basable_core::Ctx,
        >
        + ::basable_messenger::Route<
            SendNotificationRequest,
            Result<NotificationReceipt, basable_core::AppError>,
            source::Order,
            basable_core::Ctx,
        > + ::basable_messenger::Route<OrderEvent, (), source::Order, basable_core::Ctx>
        + Sync,
{}
/// The sender of `order`: exactly its declared sends, each a direct call into the router's route.
pub struct OrderSender<'a, R>(&'a R);
impl<'a, R> Clone for OrderSender<'a, R> {
    fn clone(&self) -> Self {
        *self
    }
}
impl<'a, R> Copy for OrderSender<'a, R> {}
impl<'a, R> OrderSender<'a, R> {
    /// Wraps the router. The messenger constructs one per handled
    /// message; a sends-only nanoservice constructs its own from
    /// the `&'static` router it was handed.
    pub fn new(router: &'a R) -> Self {
        OrderSender(router)
    }
}
impl<'a, R: OrderRoutes> OrderSender<'a, R> {
    /// Sends `GetProductRequest`: a 1:1 request.
    pub async fn send_get_product_request(
        &self,
        ctx: &basable_core::Ctx,
        msg: GetProductRequest,
    ) -> Result<Product, basable_core::AppError> {
        <R as ::basable_messenger::Route<
            GetProductRequest,
            Result<Product, basable_core::AppError>,
            source::Order,
            basable_core::Ctx,
        >>::route(self.0, ctx, msg)
            .await
    }
    /// Sends `SendNotificationRequest`: a 1:1 request.
    pub async fn send_send_notification_request(
        &self,
        ctx: &basable_core::Ctx,
        msg: SendNotificationRequest,
    ) -> Result<NotificationReceipt, basable_core::AppError> {
        <R as ::basable_messenger::Route<
            SendNotificationRequest,
            Result<NotificationReceipt, basable_core::AppError>,
            source::Order,
            basable_core::Ctx,
        >>::route(self.0, ctx, msg)
            .await
    }
    /// Sends `OrderEvent`: a void fan-out (every handler in declaration order).
    pub async fn send_order_event(&self, ctx: &basable_core::Ctx, msg: OrderEvent) {
        <R as ::basable_messenger::Route<
            OrderEvent,
            (),
            source::Order,
            basable_core::Ctx,
        >>::route(self.0, ctx, msg)
            .await
    }
}
/// What `order` implements: one method per handled message, generic over the router it sends through. The future is `Send`, so a `std::sync::MutexGuard` cannot be held across a send.
pub trait OrderHandler<R: OrderRoutes>: Send + Sync {
    /// Handles `EnsureOrderRequest`: the one handler of this 1:1 request. `s` is this nanoservice's sender.
    fn handle_ensure_order_request(
        &self,
        ctx: &basable_core::Ctx,
        msg: EnsureOrderRequest,
        s: OrderSender<'_, R>,
    ) -> impl ::std::future::Future<
        Output = Result<Order, basable_core::AppError>,
    > + Send;
    /// Handles `CancelOrderRequest`: the one handler of this 1:1 request. `s` is this nanoservice's sender.
    fn handle_cancel_order_request(
        &self,
        ctx: &basable_core::Ctx,
        msg: CancelOrderRequest,
        s: OrderSender<'_, R>,
    ) -> impl ::std::future::Future<
        Output = Result<Order, basable_core::AppError>,
    > + Send;
}
/// What `notifier` needs of the router: a route for each of its 0 declared send(s). Every router the generator emits satisfies it (blanket impl).
pub trait NotifierRoutes: Sync {}
impl<T> NotifierRoutes for T
where
    T: Sync,
{}
/// The sender of `notifier`: exactly its declared sends, each a direct call into the router's route.
pub struct NotifierSender<'a, R>(&'a R);
impl<'a, R> Clone for NotifierSender<'a, R> {
    fn clone(&self) -> Self {
        *self
    }
}
impl<'a, R> Copy for NotifierSender<'a, R> {}
impl<'a, R> NotifierSender<'a, R> {
    /// Wraps the router. The messenger constructs one per handled
    /// message; a sends-only nanoservice constructs its own from
    /// the `&'static` router it was handed.
    pub fn new(router: &'a R) -> Self {
        NotifierSender(router)
    }
}
/// What `notifier` implements: one method per handled message, generic over the router it sends through. The future is `Send`, so a `std::sync::MutexGuard` cannot be held across a send.
pub trait NotifierHandler<R: NotifierRoutes>: Send + Sync {
    /// Handles `SendNotificationRequest`: the one handler of this 1:1 request. `s` is this nanoservice's sender.
    fn handle_send_notification_request(
        &self,
        ctx: &basable_core::Ctx,
        msg: SendNotificationRequest,
        s: NotifierSender<'_, R>,
    ) -> impl ::std::future::Future<
        Output = Result<NotificationReceipt, basable_core::AppError>,
    > + Send;
    /// Handles `OrderEvent`: one handler of this void fan-out. `s` is this nanoservice's sender.
    fn handle_order_event(
        &self,
        ctx: &basable_core::Ctx,
        msg: OrderEvent,
        s: NotifierSender<'_, R>,
    ) -> impl ::std::future::Future<Output = ()> + Send;
}
/// What `api` needs of the router: a route for each of its 3 declared send(s). Every router the generator emits satisfies it (blanket impl).
pub trait ApiRoutes: ::basable_messenger::Route<
        UpsertProductRequest,
        Result<Product, basable_core::AppError>,
        source::Api,
        basable_core::Ctx,
    > + ::basable_messenger::Route<
        EnsureOrderRequest,
        Result<Order, basable_core::AppError>,
        source::Api,
        basable_core::Ctx,
    > + ::basable_messenger::Route<
        CancelOrderRequest,
        Result<Order, basable_core::AppError>,
        source::Api,
        basable_core::Ctx,
    > + Sync {}
impl<T> ApiRoutes for T
where
    T: ::basable_messenger::Route<
            UpsertProductRequest,
            Result<Product, basable_core::AppError>,
            source::Api,
            basable_core::Ctx,
        >
        + ::basable_messenger::Route<
            EnsureOrderRequest,
            Result<Order, basable_core::AppError>,
            source::Api,
            basable_core::Ctx,
        >
        + ::basable_messenger::Route<
            CancelOrderRequest,
            Result<Order, basable_core::AppError>,
            source::Api,
            basable_core::Ctx,
        > + Sync,
{}
/// The sender of `api`: exactly its declared sends, each a direct call into the router's route.
pub struct ApiSender<'a, R>(&'a R);
impl<'a, R> Clone for ApiSender<'a, R> {
    fn clone(&self) -> Self {
        *self
    }
}
impl<'a, R> Copy for ApiSender<'a, R> {}
impl<'a, R> ApiSender<'a, R> {
    /// Wraps the router. The messenger constructs one per handled
    /// message; a sends-only nanoservice constructs its own from
    /// the `&'static` router it was handed.
    pub fn new(router: &'a R) -> Self {
        ApiSender(router)
    }
}
impl<'a, R: ApiRoutes> ApiSender<'a, R> {
    /// Sends `UpsertProductRequest`: a 1:1 request.
    pub async fn send_upsert_product_request(
        &self,
        ctx: &basable_core::Ctx,
        msg: UpsertProductRequest,
    ) -> Result<Product, basable_core::AppError> {
        <R as ::basable_messenger::Route<
            UpsertProductRequest,
            Result<Product, basable_core::AppError>,
            source::Api,
            basable_core::Ctx,
        >>::route(self.0, ctx, msg)
            .await
    }
    /// Sends `EnsureOrderRequest`: a 1:1 request.
    pub async fn send_ensure_order_request(
        &self,
        ctx: &basable_core::Ctx,
        msg: EnsureOrderRequest,
    ) -> Result<Order, basable_core::AppError> {
        <R as ::basable_messenger::Route<
            EnsureOrderRequest,
            Result<Order, basable_core::AppError>,
            source::Api,
            basable_core::Ctx,
        >>::route(self.0, ctx, msg)
            .await
    }
    /// Sends `CancelOrderRequest`: a 1:1 request.
    pub async fn send_cancel_order_request(
        &self,
        ctx: &basable_core::Ctx,
        msg: CancelOrderRequest,
    ) -> Result<Order, basable_core::AppError> {
        <R as ::basable_messenger::Route<
            CancelOrderRequest,
            Result<Order, basable_core::AppError>,
            source::Api,
            basable_core::Ctx,
        >>::route(self.0, ctx, msg)
            .await
    }
}
