// GENERATED by basable-messenger-gen from routing.yaml. DO NOT EDIT.
// Edit routing.yaml and rebuild; the build regenerates this file.

#![allow(unused_imports, clippy::needless_lifetimes)]
use ::basable_messenger::{boxed, Route};
use ::interfaces::source;
use messages::*;
/// The router: every nanoservice's component, one `Route` impl per declared `(source, message)` pair, and the `basable_app::Components` impl that hands the app every component's loops. Fields are private, so a handler holding `&AppMessenger` reaches only its own sender.
pub struct AppMessenger {
    catalog: catalog::Catalog,
    order: order::Order,
    notifier: notifier::Notifier,
    api: api::Api,
}
impl AppMessenger {
    /// Builds the router from every component, in `routing.yaml` order.
    pub fn new(
        catalog: catalog::Catalog,
        order: order::Order,
        notifier: notifier::Notifier,
        api: api::Api,
    ) -> Self {
        AppMessenger {
            catalog,
            order,
            notifier,
            api,
        }
    }
    /// The `catalog` component (for the composition root: the Connect server, the raw routes).
    pub fn catalog(&self) -> &catalog::Catalog {
        &self.catalog
    }
    /// The `order` component (for the composition root: the Connect server, the raw routes).
    pub fn order(&self) -> &order::Order {
        &self.order
    }
    /// The `notifier` component (for the composition root: the Connect server, the raw routes).
    pub fn notifier(&self) -> &notifier::Notifier {
        &self.notifier
    }
    /// The `api` component (for the composition root: the Connect server, the raw routes).
    pub fn api(&self) -> &api::Api {
        &self.api
    }
}
/// Every component's loops, one entry per nanoservice in `routing.yaml` order and named as there: what `basable_app::Serve::components` registers, each loop as `<name>/<loop>`. A component that owns no loops takes `Component`'s default.
impl ::basable_app::Components for AppMessenger {
    fn loops(&'static self) -> Vec<(&'static str, ::basable_app::Loops)> {
        Vec::from([
            ("catalog", ::basable_app::Component::<Self>::loops(&self.catalog, self)),
            ("order", ::basable_app::Component::<Self>::loops(&self.order, self)),
            ("notifier", ::basable_app::Component::<Self>::loops(&self.notifier, self)),
            ("api", ::basable_app::Component::<Self>::loops(&self.api, self)),
        ])
    }
}
#[allow(dead_code)]
fn assert_components_are_send_and_sync() {
    fn check<T: Send + Sync>() {}
    check::<catalog::Catalog>();
    check::<order::Order>();
    check::<notifier::Notifier>();
    check::<api::Api>();
}
/// `GetProductRequest` sent by `order`: 1:1 to `catalog`.
impl Route<
    GetProductRequest,
    Result<Product, basable_core::AppError>,
    source::Order,
    basable_core::Ctx,
> for AppMessenger {
    async fn route(
        &self,
        ctx: &basable_core::Ctx,
        msg: GetProductRequest,
    ) -> Result<Product, basable_core::AppError> {
        ::interfaces::CatalogHandler::<
            AppMessenger,
        >::handle_get_product_request(
                &self.catalog,
                ctx,
                msg,
                ::interfaces::CatalogSender::new(self),
            )
            .await
    }
}
/// `SendNotificationRequest` sent by `order`: 1:1 to `notifier`.
impl Route<
    SendNotificationRequest,
    Result<NotificationReceipt, basable_core::AppError>,
    source::Order,
    basable_core::Ctx,
> for AppMessenger {
    async fn route(
        &self,
        ctx: &basable_core::Ctx,
        msg: SendNotificationRequest,
    ) -> Result<NotificationReceipt, basable_core::AppError> {
        ::interfaces::NotifierHandler::<
            AppMessenger,
        >::handle_send_notification_request(
                &self.notifier,
                ctx,
                msg,
                ::interfaces::NotifierSender::new(self),
            )
            .await
    }
}
/// `OrderEvent` sent by `order`: void fan-out to [catalog, notifier].
impl Route<OrderEvent, (), source::Order, basable_core::Ctx> for AppMessenger {
    async fn route(&self, ctx: &basable_core::Ctx, msg: OrderEvent) {
        ::interfaces::CatalogHandler::<
            AppMessenger,
        >::handle_order_event(
                &self.catalog,
                ctx,
                msg.clone(),
                ::interfaces::CatalogSender::new(self),
            )
            .await;
        ::interfaces::NotifierHandler::<
            AppMessenger,
        >::handle_order_event(
                &self.notifier,
                ctx,
                msg,
                ::interfaces::NotifierSender::new(self),
            )
            .await;
    }
}
/// `UpsertProductRequest` sent by `api`: 1:1 to `catalog`.
impl Route<
    UpsertProductRequest,
    Result<Product, basable_core::AppError>,
    source::Api,
    basable_core::Ctx,
> for AppMessenger {
    async fn route(
        &self,
        ctx: &basable_core::Ctx,
        msg: UpsertProductRequest,
    ) -> Result<Product, basable_core::AppError> {
        ::interfaces::CatalogHandler::<
            AppMessenger,
        >::handle_upsert_product_request(
                &self.catalog,
                ctx,
                msg,
                ::interfaces::CatalogSender::new(self),
            )
            .await
    }
}
/// `EnsureOrderRequest` sent by `api`: 1:1 to `order`.
impl Route<
    EnsureOrderRequest,
    Result<Order, basable_core::AppError>,
    source::Api,
    basable_core::Ctx,
> for AppMessenger {
    async fn route(
        &self,
        ctx: &basable_core::Ctx,
        msg: EnsureOrderRequest,
    ) -> Result<Order, basable_core::AppError> {
        ::interfaces::OrderHandler::<
            AppMessenger,
        >::handle_ensure_order_request(
                &self.order,
                ctx,
                msg,
                ::interfaces::OrderSender::new(self),
            )
            .await
    }
}
/// `CancelOrderRequest` sent by `api`: 1:1 to `order`.
impl Route<
    CancelOrderRequest,
    Result<Order, basable_core::AppError>,
    source::Api,
    basable_core::Ctx,
> for AppMessenger {
    async fn route(
        &self,
        ctx: &basable_core::Ctx,
        msg: CancelOrderRequest,
    ) -> Result<Order, basable_core::AppError> {
        ::interfaces::OrderHandler::<
            AppMessenger,
        >::handle_cancel_order_request(
                &self.order,
                ctx,
                msg,
                ::interfaces::OrderSender::new(self),
            )
            .await
    }
}
